version: 2.1
jobs:
  build:
    docker:
      - image: brewdamaster/circleci-demo:gcloud-sdk

  # context / project UI env-var reference
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: false

      # build and push Docker image
      - run: |
          source /etc/environment
          docker pull brewdamaster/circleci-demo:button-demo
          gcloud auth activate-service-account --key-file=$GCLOUD_SERVICE_KEY
          gcloud --quiet config set project $GOOGLE_PROJECT_ID
          gcloud --quiet config set compute/zone $GOOGLE_COMPUTE_ZONE
          docker tag brewdamaster/circleci-demo gcr.io/circleci-demo-297514/button-demo
          gcloud docker push gcr.io/circleci-demo-297514/button-demo
